name: Ansible Deployment

on:
  workflow_dispatch:
    inputs:
      remote-host-ip:
        description: "IP address of the remote host"
        required: true
      aws-account:
        description: "Select AWS Account (dev, sit, prod)"
        required: true
        default: "dev"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_DEV_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download SSH private key from S3
        run: |
          aws s3 cp s3://${{ secrets.BUCKET_NAME }}/keys/webserver-key /tmp/webserver-key
          base64 -d /tmp/webserver-key >> /tmp/key.pem
          cat /tmp/key.pem

      - name: Set permissions for SSH key
        run: |
          chmod 600 /tmp/key.pem

      - name: Create temporary inventory file
        run: |
          echo "[webserver]" > /tmp/inventory
          echo "${{ github.event.inputs.remote-host-ip }} ansible_user="ubuntu" ansible_port="22" ansible_ssh_private_key_file="/tmp/key.pem"" >> /tmp/inventory
          export ANSIBLE_HOST_KEY_CHECKING=False

      - name: Run Ansible playbook
        run: |
          cd ansible
          ansible-playbook lemp_stack.yml -i /tmp/inventory

      - name: Clean up temporary files
        run: |
          rm -f /tmp/inventory /tmp/key.pem /tmp/webserver-key
