name: Ansible Deployment

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    inputs:
      remote-host-ip:
        description: "IP address of the remote host"
        required: true
      aws-account:
        description: "Select AWS Account (dev, sit, prod)"
        required: true
        default: "dev"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_DEV_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download SSH private key from S3
        run: |
          aws s3 cp s3://${{ secrets.BUCKET_NAME }}/keys/wordpress-nginx-key /tmp/key.pem

      - name: Set permissions for SSH key
        run: |
          chmod 600 /tmp/key.pem

      - name: Run Ansible playbook
        run: |
          cd ansible
          ansible-playbook lemp_stack.yml \
            -i ${{ github.event.inputs.remote-host-ip }} \
            --key-file=/tmp/key.pem \
            -e "ansible_ssh_common_args='-o StrictHostKeyChecking=no'"
          rm -f /tmp/key.pem
