name: Ansible Deployment

on:
  workflow_dispatch:
    inputs:
      remote-host-ip:
        description: "IP address of the remote host"
        required: true
      aws-account:
        description: "Select AWS Account (dev, sit, prod)"
        required: true
        default: "dev"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ github.event.inputs.remote-host-ip }}" > ~/.ssh/known_hosts

      - name: Create temporary inventory file
        run: |
          cd ansible
          echo "[webserver]" >> inventory
          echo "${{ github.event.inputs.remote-host-ip }} ansible_user='ubuntu' ansible_port='22' ansible_ssh_private_key_file='~/.ssh/id_rsa'" >> inventory
          export ANSIBLE_HOST_KEY_CHECKING=False

      - name: Ping host machines
        run: |
          cd ansible
          ansible all -m ping -i inventory --ssh-common-args='-o StrictHostKeyChecking=no'

      - name: Run Ansible playbook
        run: |
          cd ansible
          ansible-playbook lemp_stack.yml -i inventory --ssh-common-args='-o StrictHostKeyChecking=no'

      - name: Clean up temporary files
        run: |
          cd ansible
          rm -f inventory
          rm -f ~/.ssh/id_rsa
